#!/bin/bash
# User setup script.
# (C) Mark Blakeney, markb@berlios.de, Aug 2016.

PROG="$(basename $0)"
NAME=${PROG%-setup}

BINDIR="/usr/bin"
APPDIR="/usr/share/applications"
ICODIR="/usr/share/pixmaps"
DOCDIR="/usr/share/doc/$NAME"
CNFDIR="/etc"
AUTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/autostart"

usage() {
    echo "Usage: $PROG install|uninstall|start|stop|autostart|autostop"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

cmd="$1"

user_action() {
    local cmd=$1

    if [ $cmd = "start" ]; then
	if [ ! -f $APPDIR/$NAME.desktop ]; then
	    echo "$NAME is not installed."
	    exit 1
	fi
	if gtk-launch "$NAME"; then
	    echo "$NAME started."
	fi
    elif [ $cmd = "stop" ]; then
	for prog in libinput-debug-events $NAME; do
	    if pkill -f "$prog " &>/dev/null; then
		echo "$prog stopped"
	    fi
	done
    elif [ $cmd = "autostart" ]; then
	if [ ! -f $APPDIR/$NAME.desktop ] ; then
	    echo "$NAME is not installed."
	    exit 1
	fi
	if ! cmp -s $APPDIR/$NAME.desktop $AUTDIR/$NAME.desktop; then
	    mkdir -p $AUTDIR
	    ln -sf -t $AUTDIR $APPDIR/$NAME.desktop
	    echo "installed or updated $AUTDIR/$NAME.desktop"
	fi
    elif [ $cmd = "autostop" ]; then
	rm -fv $AUTDIR/$NAME.desktop
    else
	usage
    fi
}

if [ $cmd = "install" -o $cmd = "uninstall" ]; then
    if [ "$(id -un)" != "root" ]; then
	echo "Install or uninstall must be run as sudo/root."
	exit 1
    fi

    if [ $cmd = "install" ]; then
	install -CDv -m 755 -t $BINDIR $NAME-setup
	install -CDv -m 755 -t $BINDIR $NAME
	install -CDv -m 644 -t $APPDIR $NAME.desktop
	install -CDv -m 644 -t $ICODIR $NAME.png
	install -CDv -m 644 -t $CNFDIR $NAME.conf
	install -CDv -m 644 -t $DOCDIR README.md
    else
	rm -rfv $BINDIR/$NAME
	rm -rfv $APPDIR/$NAME.desktop
	rm -rfv $ICODIR/$NAME.png
	rm -rfv $CNFDIR/$NAME.conf
	rm -rfv $DOCDIR
	rm -rfv $BINDIR/$NAME-setup
    fi

    if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q
    fi
else
    if [ "$(id -un)" = "root" ]; then
	echo "Non-installation commands must run as your own user."
	exit 1
    fi

    # Remove any old configuration from earlier versions of program
    rm -fv ~/bin/$NAME
    rm -fv ~/.local/bin/$NAME
    rm -fv ~/.local/share/applications/$NAME.desktop
    rm -fv ~/.local/share/icons/$NAME.png

    if [ $cmd = "restart" ]; then
	user_action "stop"
	user_action "start"
    else
	user_action $cmd
    fi
fi

exit 0
